{% set name = "qsv" %}
{% set version = "0.133.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jqnatividad/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: ef21b43cd0cd01e926333a35ed4ac8529f9cc602c4fb3e911e6592e79c14004f

build:
  number: 0
  skip: true  # [win]
  ignore_run_exports:
    - libclang

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - python                                # [build_platform != target_platform]
  host:
    - libclang
    - libiconv  # [osx]
    - python
  run:
    - python

test:
  commands:
    - {{ name }} --help

about:
  home: https://github.com/jqnatividad/{{ name }}
  license: MIT
  license_file: LICENSE-MIT
  summary: Ultra-fast CSV data-wrangling toolkit
  dev_url: https://github.com/jqnatividad/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
