{% set name = "qsv" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jqnatividad/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 92ca4fef2c0f58aa5d322a01a70a7e9dd689f8055cdf64aaf1422cb28fe5357b

build:
  number: 0
  skip: true  # [win]
  ignore_run_exports:
    - libclang

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - python                                # [build_platform != target_platform]
  host:
    - libclang
    - libiconv  # [osx]
    - python
  run:
    - python

test:
  commands:
    - {{ name }} --help

about:
  home: https://github.com/jqnatividad/{{ name }}
  license: MIT
  license_file: LICENSE-MIT
  summary: Ultra-fast CSV data-wrangling toolkit
  dev_url: https://github.com/jqnatividad/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
