{% set name = "qsv" %}
{% set version = "0.132.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jqnatividad/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: bc7a1405a1543a6930d3478d80288d213acc3104a0510a7bceffc2bb32b972e0

build:
  number: 0
  skip: true  # [win]
  ignore_run_exports:
    - libclang

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - python                                # [build_platform != target_platform]
  host:
    - libclang
    - libiconv  # [osx]
    - python
  run:
    - python

test:
  commands:
    - {{ name }} --help

about:
  home: https://github.com/jqnatividad/{{ name }}
  license: MIT
  license_file: LICENSE-MIT
  summary: Ultra-fast CSV data-wrangling toolkit
  dev_url: https://github.com/jqnatividad/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
