context:
  version: "5.1.0"

package:
  name: qsv
  version: ${{ version }}

source:
  url: https://github.com/jqnatividad/qsv/archive/${{ version }}.tar.gz
  sha256: 9bed0898cce8de237a0a04f8d28947720dbb6d0b2919cf297007a1a57569dfd2

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('rust') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - cmake
    - make
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
        - python
    - pkg-config
  host:
    - libclang
    - if: osx
      then: libiconv
    - python
    - if: linux
      then: wayland
  run:
    - python
  ignore_run_exports:
    from_package:
      - libclang

tests:
  - script:
      - qsv --help

about:
  license: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: Ultra-fast CSV data-wrangling toolkit
  homepage: https://github.com/jqnatividad/qsv
  repository: https://github.com/jqnatividad/qsv

extra:
  recipe-maintainers:
    - danielnachun
