context:
  version: "7.0.1"

package:
  name: qsv
  version: ${{ version }}

source:
  url: https://github.com/jqnatividad/qsv/archive/${{ version }}.tar.gz
  sha256: f6dc3ca7dc227a3ff325464c8861cdc3f1e3d051857bed3882ba041804af4822

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('rust') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - cmake
    - libclang  # only used for a build binary
    - make
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
        - python
    - pkg-config
  host:
    - if: osx
      then: libiconv
    - python
    - if: linux
      then: wayland
  run:
    - python

tests:
  - script:
      - qsv --help

about:
  license: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: Ultra-fast CSV data-wrangling toolkit
  homepage: https://github.com/jqnatividad/qsv
  repository: https://github.com/jqnatividad/qsv

extra:
  recipe-maintainers:
    - danielnachun
