azure:
  free_disk_space: true
  settings_win:
    variables:
      SET_PAGEFILE: "True"
  settings_linux:
    swapfile_size: 16GiB
bot:
  automerge: true
build_platform:
  linux_aarch64: linux_64
conda_build:
  error_overlinking: true
conda_build_tool: rattler-build
conda_forge_output_validation: true
conda_install_tool: pixi
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: azure
test: native_and_emulated
