azure:
  free_disk_space: true
  settings_win:
    variables:
      SET_PAGEFILE: "True"
  settings_linux:
    swapfile_size: 16GiB
bot:
  automerge: true
conda_build:
  error_overlinking: true
conda_build_tool: rattler-build
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
test: native_and_emulated
